name: test-on-hardware-linux-pc

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  test-on-hardware:
    runs-on: 
      - self-hosted
      - linux
      - ubuntu
      - hw_mlx90641
    steps:
    - uses: actions/checkout@v2
